# Generated by Django 2.0.2 on 2018-03-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
    ]
