# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180517_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='img/profile/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.TextField(),
        ),
    ]
